version: "3.8"

services:

  configserver:
    image: wsktang/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
     - wttc
      
  accounts:
    image: wsktang/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - wttc
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

networks:
  wttc: